### ISSUE TITLE
Error Building your own Lithops runtime for Google Cloud Functions

### ISSUE THREAD

**Issue by AaronSoria** [lithops-cloud/lithops#1004] opened 2022-11-05 11:08 UTC
lithops version 2.7.0
python version 3.9.2
debian 11

I'm trying to run the following command:

lithops runtime build -f requirements.txt -b gcp_functions my_Image_runtime -s gcp_storage

and I'm getting the following error
```
2022-11-05 08:02:56,108 [DEBUG] utils.py:228 -- Creating function handler zip in /tmp/lithops_gcp_functions.zip
Traceback (most recent call last):
  File "/home/allen28/pruebas_master/proc_img/env/bin/lithops", line 8, in <module>
    sys.exit(lithops_cli())
  File "/home/allen28/pruebas_master/proc_img/env/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/allen28/pruebas_master/proc_img/env/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/allen28/pruebas_master/proc_img/env/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/allen28/pruebas_master/proc_img/env/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/allen28/pruebas_master/proc_img/env/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/allen28/pruebas_master/proc_img/env/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/allen28/pruebas_master/proc_img/env/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/allen28/pruebas_master/proc_img/env/lib/python3.9/site-packages/lithops/scripts/cli.py", line 451, in build
    compute_handler.build_runtime(runtime_name, file, ctx.args)
  File "/home/allen28/pruebas_master/proc_img/env/lib/python3.9/site-packages/lithops/serverless/serverless.py", line 71, in build_runtime
    self.backend.build_runtime(runtime_name, file, extra_args)
  File "/home/allen28/pruebas_master/proc_img/env/lib/python3.9/site-packages/lithops/serverless/backends/gcp_functions/gcp_functions.py", line 256, in build_runtime
    self.internal_storage.put_data(bin_location, action_bin)
AttributeError: 'NoneType' object has no attribute 'put_data'
```

**Comment by JosepSampe** [comment] 2022-11-05 11:36
@AaronSoria The issue is already fixed on master branch https://github.com/lithops-cloud/lithops/pull/1003

**Closed** 2022-11-06 13:10 UTC
