### ISSUE TITLE
.get_results() error on code engine

### ISSUE THREAD

**Issue by ShuxinLin** [lithops-cloud/lithops#598] opened 2021-03-10 17:35 UTC
I encountered the following error occasionally when `.get_results()` is called. The backend is IBM code engine. I monitored the jobrun very closely and can confirm the jobs were completed successfully. What could be the reason? Lithops version is 2.3.0.

```
  File "/Users/shuxin.lin/Projects/srom-forked/srom/pipeline/execution_types/srom_lithops_search.py", line 214, in run
    ans = remote_executor.get_result(throw_except=False)
  File "/Users/shuxin.lin/.pyenv/versions/anaconda3-5.3.0/envs/lithops_cf/lib/python3.7/site-packages/lithops/executors.py", line 493, in get_result
    WAIT_DUR_SEC=WAIT_DUR_SEC)
  File "/Users/shuxin.lin/.pyenv/versions/anaconda3-5.3.0/envs/lithops_cf/lib/python3.7/site-packages/lithops/executors.py", line 452, in wait
    raise e
  File "/Users/shuxin.lin/.pyenv/versions/anaconda3-5.3.0/envs/lithops_cf/lib/python3.7/site-packages/lithops/executors.py", line 430, in wait
    THREADPOOL_SIZE=THREADPOOL_SIZE, WAIT_DUR_SEC=WAIT_DUR_SEC)
  File "/Users/shuxin.lin/.pyenv/versions/anaconda3-5.3.0/envs/lithops_cf/lib/python3.7/site-packages/lithops/wait/wait_storage.py", line 91, in wait_storage
    THREADPOOL_SIZE=THREADPOOL_SIZE)
  File "/Users/shuxin.lin/.pyenv/versions/anaconda3-5.3.0/envs/lithops_cf/lib/python3.7/site-packages/lithops/wait/wait_storage.py", line 247, in _wait_storage
    list(pool.map(get_result, fs_to_wait_on))
  File "/Users/shuxin.lin/.pyenv/versions/anaconda3-5.3.0/envs/lithops_cf/lib/python3.7/concurrent/futures/_base.py", line 598, in result_iterator
    yield fs.pop().result()
  File "/Users/shuxin.lin/.pyenv/versions/anaconda3-5.3.0/envs/lithops_cf/lib/python3.7/concurrent/futures/_base.py", line 435, in result
    return self.__get_result()
  File "/Users/shuxin.lin/.pyenv/versions/anaconda3-5.3.0/envs/lithops_cf/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/Users/shuxin.lin/.pyenv/versions/anaconda3-5.3.0/envs/lithops_cf/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/shuxin.lin/.pyenv/versions/anaconda3-5.3.0/envs/lithops_cf/lib/python3.7/site-packages/lithops/wait/wait_storage.py", line 239, in get_result
    f.result(throw_except=throw_except, internal_storage=internal_storage)
  File "/Users/shuxin.lin/.pyenv/versions/anaconda3-5.3.0/envs/lithops_cf/lib/python3.7/site-packages/lithops/future.py", line 284, in result
    self.status(throw_except=throw_except, internal_storage=internal_storage)
  File "/Users/shuxin.lin/.pyenv/versions/anaconda3-5.3.0/envs/lithops_cf/lib/python3.7/site-packages/lithops/future.py", line 175, in status
    if self._call_status['logs']:
KeyError: 'logs'

Process finished with exit code 1

```

**Comment by gilv** [comment] 2021-03-10 17:37
@JosepSampe what might cause it?

**Comment by JosepSampe** [comment] 2021-03-10 17:38
The principal reason might be you are using a runtime build with a lithops version < 2.3.0. Is this possible?

**Comment by gilv** [comment] 2021-03-10 17:40
@ShuxinLin what runtime you use? The one you build yourself?

**Comment by ShuxinLin** [comment] 2021-03-10 17:40
I built a new runtime on the latest lithops. And it worked most of the time. But sometimes it failed due to the error above

**Comment by gilv** [comment] 2021-03-10 17:45
@JosepSampe why you think it related runtime with <2.3.0..is this some recent change?

**Comment by ShuxinLin** [comment] 2021-03-10 17:49
I think it might be related to code 
```
ans = remote_executor.get_result(throw_except=False)
remote_executor.clean()
```
Did `.clean()` got blocked until `.get_result()` returns?
@gilv @JosepSampe

**Comment by JosepSampe** [comment] 2021-03-10 17:53
@gilv Yes, this is an addition in 2.3.0
@ShuxinLin No, the clean operation does not cause the error. This is caused by the remote worker not including logs on the response. 

I will add a fix to prevent this

**Comment by ShuxinLin** [comment] 2021-03-10 17:57
@JosepSampe 
I found `.get_result()` will delete configmap and jobrun after the job finishs on Code Engine.
Is this new in the latest lithops?

**Comment by JosepSampe** [comment] 2021-03-10 18:04
@ShuxinLin Yes, this is done automatically after each get_result() since there is a limitation of 10 configamps in Code Engine, so better delete them once the job is finished. 

In any case, you can disable this automation by setting in your config:
```yaml
lithops:
    data_cleaner: false
```
If you set it to false, then the you should think to manually call `remote_executor.clean()`

**Comment by ShuxinLin** [comment] 2021-03-10 18:07
Okay. So no need to do `.clean()` after `get_result()`. Got it!

**Comment by JosepSampe** [comment] 2021-03-10 18:09
@ShuxinLin Yep, by default `data_cleaner` is set to True, so` .clean()` is redundant and does nothing since at that point everything is already cleaned.

**Comment by JosepSampe** [comment] 2021-03-10 23:17
@ShuxinLin This should be fixed on master branch

**Closed** 2021-03-16 09:18 UTC
