### ISSUE TITLE
[GCP] Error while deploying Cloud Function

### ISSUE THREAD

**Issue by gfinol** [lithops-cloud/lithops#1002] opened 2022-11-03 12:27 UTC
Once I have everything set up following the instructions (lithops version 2.7.0 and python 3.9.13). 

I run a `lithops test` and I get an error saying "`Error while deploying Cloud Function`".
<details>
  <summary>Click to see error trace</summary> 

```
    2022-11-03 13:03:33,899 [INFO] config.py:131 -- Lithops v2.7.0
    2022-11-03 13:03:34,195 [INFO] gcp_storage.py:45 -- Google Cloud Storage client created
    2022-11-03 13:03:34,276 [INFO] gcp_functions.py:56 -- Google Cloud Functions client created - Region: us-east1 - Project: gfinol-lithops-debug
    2022-11-03 13:03:34,276 [INFO] invokers.py:108 -- ExecutorID 562265-0 | JobID A000 - Selected Runtime: lithops-default-runtime-v39 - 256MB
    2022-11-03 13:03:34,810 [INFO] invokers.py:116 -- Runtime lithops-default-runtime-v39 with 256MB is not yet deployed
    2022-11-03 13:03:34,810 [INFO] gcp_functions.py:273 -- Deploying runtime: lithops-default-runtime-v39 - Memory: 256 Timeout: 300
    2022-11-03 13:03:34,811 [INFO] gcp_functions.py:241 -- Building runtime lithops-default-runtime-v39 from /tmp/gcf_default_requirements.txt
    2022-11-03 13:04:37,617 [INFO] gcp_functions.py:225 -- Waiting for the function to be deployed
    Traceback (most recent call last):
    File "/home/gerard/.anaconda3/envs/py39/bin/lithops", line 8, in <module>
        sys.exit(lithops_cli())
    File "/home/gerard/.anaconda3/envs/py39/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
        return self.main(*args, **kwargs)
    File "/home/gerard/.anaconda3/envs/py39/lib/python3.9/site-packages/click/core.py", line 1055, in main
        rv = self.invoke(ctx)
    File "/home/gerard/.anaconda3/envs/py39/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
    File "/home/gerard/.anaconda3/envs/py39/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
        return ctx.invoke(self.callback, **ctx.params)
    File "/home/gerard/.anaconda3/envs/py39/lib/python3.9/site-packages/click/core.py", line 760, in invoke
        return __callback(*args, **kwargs)
    File "/home/gerard/.anaconda3/envs/py39/lib/python3.9/site-packages/lithops/scripts/cli.py", line 173, in test_function
        fexec.call_async(hello, username)
    File "/home/gerard/.anaconda3/envs/py39/lib/python3.9/site-packages/lithops/executors.py", line 209, in call_async
        runtime_meta = self.invoker.select_runtime(job_id, runtime_memory)
    File "/home/gerard/.anaconda3/envs/py39/lib/python3.9/site-packages/lithops/invokers.py", line 117, in select_runtime
        runtime_meta = self.compute_handler.deploy_runtime(self.runtime_name, runtime_memory, runtime_timeout)
    File "/home/gerard/.anaconda3/envs/py39/lib/python3.9/site-packages/lithops/serverless/serverless.py", line 73, in deploy_runtime
        return self.backend.deploy_runtime(runtime_name, memory, timeout=timeout)
    File "/home/gerard/.anaconda3/envs/py39/lib/python3.9/site-packages/lithops/serverless/backends/gcp_functions/gcp_functions.py", line 278, in deploy_runtime
        self._create_function(runtime_name, memory, timeout)
    File "/home/gerard/.anaconda3/envs/py39/lib/python3.9/site-packages/lithops/serverless/backends/gcp_functions/gcp_functions.py", line 234, in _create_function
        raise Exception('Error while deploying Cloud Function')
    Exception: Error while deploying Cloud Function
```
</details>

This is a screenshot of the error in the Google cloud console:

![image](https://user-images.githubusercontent.com/11145254/199719323-70d11416-80bf-4d02-b9ea-01dc96591cfa.png)

I also tried to create a custom runtime using 
`lithops runtime build -f requirements.txt -b gcp_functions my_Image_runtime -s gcp_storage`

But I get a `AttributeError: 'NoneType' object has no attribute 'put_data'`. 

<details>
  <summary>Click to see error trace</summary> 

```
    2022-11-03 13:08:02,137 [INFO] config.py:131 -- Lithops v2.7.0
    2022-11-03 13:08:02,138 [DEBUG] config.py:90 -- Loading configuration from /home/gerard/.lithops/config
    2022-11-03 13:08:02,155 [DEBUG] config.py:183 -- Loading Serverless backend module: gcp_functions
    2022-11-03 13:08:02,379 [DEBUG] gcp_functions.py:79 -- Getting GCP credentials from /home/gerard/.lithops/gfinol-lithops-debug-7dea7b8f11a1.json
    2022-11-03 13:08:02,464 [INFO] gcp_functions.py:56 -- Google Cloud Functions client created - Region: us-east1 - Project: gfinol-lithops-debug
    2022-11-03 13:08:02,464 [INFO] gcp_functions.py:241 -- Building runtime my_Image_runtime from requirements.txt
    2022-11-03 13:08:02,464 [DEBUG] utils.py:228 -- Creating function handler zip in /tmp/lithops_gcp_functions.zip
    Traceback (most recent call last):
    File "/home/gerard/.anaconda3/envs/py39/bin/lithops", line 8, in <module>
        sys.exit(lithops_cli())
    File "/home/gerard/.anaconda3/envs/py39/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
        return self.main(*args, **kwargs)
    File "/home/gerard/.anaconda3/envs/py39/lib/python3.9/site-packages/click/core.py", line 1055, in main
        rv = self.invoke(ctx)
    File "/home/gerard/.anaconda3/envs/py39/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
    File "/home/gerard/.anaconda3/envs/py39/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
    File "/home/gerard/.anaconda3/envs/py39/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
        return ctx.invoke(self.callback, **ctx.params)
    File "/home/gerard/.anaconda3/envs/py39/lib/python3.9/site-packages/click/core.py", line 760, in invoke
        return __callback(*args, **kwargs)
    File "/home/gerard/.anaconda3/envs/py39/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
        return f(get_current_context(), *args, **kwargs)
    File "/home/gerard/.anaconda3/envs/py39/lib/python3.9/site-packages/lithops/scripts/cli.py", line 451, in build
        compute_handler.build_runtime(runtime_name, file, ctx.args)
    File "/home/gerard/.anaconda3/envs/py39/lib/python3.9/site-packages/lithops/serverless/serverless.py", line 66, in build_runtime
        self.backend.build_runtime(runtime_name, file, extra_args)
    File "/home/gerard/.anaconda3/envs/py39/lib/python3.9/site-packages/lithops/serverless/backends/gcp_functions/gcp_functions.py", line 254, in build_runtime
        self.internal_storage.put_data(bin_location, action_bin)
    AttributeError: 'NoneType' object has no attribute 'put_data'
```
</details>

**Comment by JosepSampe** [comment] 2022-11-03 13:21
I can't reproduce the first error. I delted everything from my account and ran lithops test and it works.

The second erros should be fixed with #1003 

```
#  lithops runtime deploy -b gcp_functions my_Image_runtime -s gcp_storage
2022-11-03 15:16:12,556 [INFO] config.py:131 -- Lithops v2.7.1.dev0
2022-11-03 15:16:12,556 [DEBUG] config.py:90 -- Loading configuration from /home/josep/.lithops/config
2022-11-03 15:16:12,573 [DEBUG] config.py:183 -- Loading Serverless backend module: gcp_functions
2022-11-03 15:16:12,876 [DEBUG] config.py:248 -- Loading Storage backend module: gcp_storage
2022-11-03 15:16:12,885 [DEBUG] gcp_storage.py:36 -- Creating GCP Storage client
2022-11-03 15:16:12,885 [DEBUG] gcp_storage.py:39 -- Getting GCP credentials from /home/josep/.lithops/lithops-dev-dac9d5b5a802.json
2022-11-03 15:16:12,919 [INFO] gcp_storage.py:45 -- Google Cloud Storage client created
2022-11-03 15:16:12,919 [DEBUG] gcp_functions.py:79 -- Getting GCP credentials from /home/josep/.lithops/lithops-dev-dac9d5b5a802.json
2022-11-03 15:16:12,987 [INFO] gcp_functions.py:56 -- Google Cloud Functions client created - Region: us-east1 - Project: lithops-dev
2022-11-03 15:16:12,987 [DEBUG] gcp_functions.py:391 -- Runtime key: gcp_functions/2.7.1.dev0/lithops-dev/us-east1/lithops_v2-7-1-dev0_my_Image_runtime_256MB
2022-11-03 15:16:12,987 [INFO] gcp_functions.py:268 -- Deploying runtime: my_Image_runtime - Memory: 256 Timeout: 300
my_Image_runtime
2022-11-03 15:16:14,494 [DEBUG] gcp_functions.py:167 -- Creating topic projects/lithops-dev/topics/lithops_v2-7-1-dev0_my_Image_runtime_256MB_us-east1_topic
2022-11-03 15:16:18,862 [DEBUG] gcp_functions.py:179 -- Creating function projects/lithops-dev/topics/lithops_v2-7-1-dev0_my_Image_runtime_256MB_us-east1_topic
2022-11-03 15:16:21,201 [DEBUG] gcp_functions.py:218 -- Creating function projects/lithops-dev/locations/us-east1/functions/lithops_v2-7-1-dev0_my_Image_runtime_256MB
2022-11-03 15:16:22,405 [INFO] gcp_functions.py:225 -- Waiting for the function to be deployed
2022-11-03 15:16:22,848 [DEBUG] gcp_functions.py:230 -- Function status is DEPLOY_IN_PROGRESS
2022-11-03 15:16:43,319 [DEBUG] gcp_functions.py:230 -- Function status is DEPLOY_IN_PROGRESS
2022-11-03 15:17:03,777 [DEBUG] gcp_functions.py:230 -- Function status is DEPLOY_IN_PROGRESS
2022-11-03 15:17:24,280 [DEBUG] gcp_functions.py:230 -- Function status is DEPLOY_IN_PROGRESS
2022-11-03 15:17:44,730 [DEBUG] gcp_functions.py:230 -- Function status is DEPLOY_IN_PROGRESS
2022-11-03 15:18:05,196 [DEBUG] gcp_functions.py:230 -- Function status is DEPLOY_IN_PROGRESS
2022-11-03 15:18:25,670 [DEBUG] gcp_functions.py:230 -- Function status is DEPLOY_IN_PROGRESS
2022-11-03 15:18:46,129 [DEBUG] gcp_functions.py:230 -- Function status is DEPLOY_IN_PROGRESS
2022-11-03 15:19:06,590 [DEBUG] gcp_functions.py:230 -- Function status is ACTIVE
2022-11-03 15:19:06,590 [DEBUG] gcp_functions.py:358 -- Extracting runtime metadata from: my_Image_runtime
2022-11-03 15:19:10,825 [DEBUG] storage.py:455 -- Uploading runtime metadata to: gcp_storage://lithops-data-us-east1/lithops.runtimes/gcp_functions/2.7.1.dev0/lithops-dev/us-east1/lithops_v2-7-1-dev0_my_Image_runtime_256MB.meta.json
2022-11-03 15:19:11,236 [DEBUG] storage.py:461 -- Storing runtime metadata into local cache: /home/josep/.lithops/cache/lithops.runtimes/gcp_functions/2.7.1.dev0/lithops-dev/us-east1/lithops_v2-7-1-dev0_my_Image_runtime_256MB.meta.json
2022-11-03 15:19:11,238 [INFO] cli.py:494 -- Runtime deployed
```

**Comment by JosepSampe** [comment] 2022-11-05 11:54
It also works for me using a new project

**Comment by JosepSampe** [comment] 2022-11-07 09:13
I created a new project and it works ok for me. Could you check in the GCP console logs if you can see why the function is not deployed correctly?

**Comment by gfinol** [comment] 2022-11-07 09:42
@JosepSampe I get the following error message:
```
    Invalid argument (HTTP 400): Build failed: *** Error compiling './lithops/storage/backends/infinispan/infinispan.py'... File "./lithops/storage/backends/infinispan/infinispan.py", line 42 match self.mech: ^ SyntaxError: invalid syntax; Error ID: 49c34848
```

**Comment by JosepSampe** [comment] 2022-11-07 09:46
Seems the "match case" feature set in the infinispan backend is only available for python > = 3.10. I'm using python3.10, thats why it doesn't fail for me. Will change it

**Comment by JosepSampe** [comment] 2022-11-07 09:52
@gfinol  I added a fix. Can you try with master branch?

**Comment by gfinol** [comment] 2022-11-07 10:09
Yes, it worked after installing from master branch. 🎉

**Closed** 2022-11-07 10:14 UTC
