### ISSUE TITLE
Failed test functions

### ISSUE THREAD

**Issue by Cohen-J-Omer** [lithops-cloud/lithops#702] opened 2021-07-14 13:54 UTC
The following tests fails to run in conjunction with a specific mode: 

1. test_map_reduce_url **fails to run on local-host mode**. 
2. test_internal_executions  **fails to run on CE** (with COS as storage).

**Comment by JosepSampe** [comment] 2021-07-14 14:37
@Cohen-J-Omer Both tests run ok by using the current [test.py](https://github.com/lithops-cloud/lithops/blob/master/lithops/scripts/tests.py) file in master branch. Is this something related to the new test files in #683 ?

**Comment by Cohen-J-Omer** [comment] 2021-07-14 15:01
Hey @JosepSampe, 
Perhaps try to run these tests after using config file instead, to simulate the way i did it? 
I have a vanilla, cloned repository of lithops, as well as my own version and from I'm getting in both:  

- "ModuleNotFoundError: No module named 'yaml' in code_engine.py" from running test_internal_executions with code_engine.
- "MemoryError: Function exceeded maximum memory and was killed" from running test_map_reduce_url on local-host.

**Comment by JosepSampe** [comment] 2021-07-14 15:26
@Cohen-J-Omer I dont' have a MAC, so I won't be able to reproduce the errors. In case of code_engie, Are you using a custom runtime? or are you using the runtime that is built by default by lithops? Could you be using a different base image that does not have the yaml package?

**Comment by Cohen-J-Omer** [comment] 2021-07-14 19:49
Sorry @JosepSampe, wish I could work tomorrow as well, but I have some matters to take care of.
In the meanwhile, perhaps you could try cloning my PR to a different branch?  
If those tests succeed in your environment, then you'll know nothing's wrong with the PR. 
Anyways, said tests are being skipped when run using the backends that might not support them, to guarantee contributors aren't wrongfully discouraged.

**Comment by Cohen-J-Omer** [comment] 2021-07-18 07:53
Good morning @JosepSampe, 
in regard to how am I building my runtime, I simply run "lithops runtime build <my_account>/<image_name>:<version> -b code_engine" from the runtime/code_engine folder, thus basing my runtime on the dockerfile within that folder. 
Finally, I record the runtime's name in my config file.

**Comment by JosepSampe** [comment] 2021-07-27 16:44
@Cohen-J-Omer How do we have o run the test now that #683 is merged? 
I tried to run this test:
```
lithops verify -b code_engine -t test_internal_executions
```
but i'm getting this message:
```
2021-07-27 18:42:19,139 [INFO] lithops.config -- Lithops v2.4.1.dev0
2021-07-27 18:42:19,753 [INFO] lithops.storage.backends.ibm_cos.ibm_cos -- IBM COS Storage client created - Region: eu-de
2021-07-27 18:42:20,576 [INFO] lithops.tests.tests_main -- Uploading datasets...
2021-07-27 18:42:20,577 [INFO] lithops.tests.tests_main -- Uploading datasets...
2021-07-27 18:42:20,578 [INFO] lithops.tests.tests_main -- Uploading datasets...
test_internal_executions (lithops.tests.test_map.TestMap) ... 
-------------------------------------------------------------

skipped 'This test function currently runs solely on Local_Host mode.'

----------------------------------------------------------------------
Ran 1 test in 0.000s

OK (skipped=1)
```

**Comment by Cohen-J-Omer** [comment] 2021-07-28 14:05
Hey @JosepSampe, 

- To debug the test function you can simply comment out the top two rows that are responsible for skipping the test. 

- Since some changes were made to CONFIG (initialized by default_config() in tests_main.py) because the version i wrote the PR on is quite dated, the test is also being skipped when run with the cloud function backend (although it does work with CF). 
A quick fix for it would be to change the first row of the function to: " if CONFIG['lithops']['backend'] == 'code_engine' ", although I guess it won't be necessary because I assume you'll figure the issue in no time. 

- I think the root of the issue might be the dockerfile (the one within runtime/code_engine) i'm building my runtime image on. 
Could it simply be missing the yaml module?

**Comment by JosepSampe** [comment] 2021-07-30 12:50
@Cohen-J-Omer I added some missing deps in [code_engine/requirements.txt](https://github.com/JosepSampe/lithops/blob/master/runtime/code_engine/requirements.txt), so now code_engine internal executions should work ok with newly built runtimes.

Regarding the localhost `test_map_reduce_url`, you should check your Lithops logs ans investigate why it fails for you, since in linux, windows and github-workflow-ubuntu it works ok. Check the functions logs and also the `...tmp/lithops/runner.log` file

**Comment by Cohen-J-Omer** [comment] 2021-08-01 08:15
- I can verify that test_internal_executions now works just fine on CE. 

- The test_map_reduce_url still fails as on my Mac. I've attached a log file. 
I'm familiar with the "private/var/.../T/lithops/logs/746ae1-0-M000.log", but I'm not aware of the "...tmp/lithops/runner.log" file. 
Could you please refer me to a documentation that mentions it?     
[logs.txt](https://github.com/lithops-cloud/lithops/files/6912341/logs.txt)

**Closed** 2021-09-16 08:17 UTC
